window.onerror = function(msg, url, line, col, error) {
    const stat = document.getElementById('status-container');
    if (stat) { stat.style.color = '#FF0033'; stat.innerText = `CRASH GEFUNDEN: ${msg} (Zeile ${line})`; }
    return false;
};

const GITHUB_JSON_URL = "https://raw.githubusercontent.com/Blackfront161/Revolution-News-Data/main/news.json";
const PROXY_URL = "https://revolution-proxy.paghklo.workers.dev";
let capVal1 = 0; let capVal2 = 0;

function changeFontSize(sizeValue) {
    document.documentElement.style.fontSize = sizeValue + "%";
    localStorage.setItem('wrn_font_zoom', sizeValue);
}

async function fetchFromGemini(promptText) {
    try {
        const response = await fetch(PROXY_URL, {
            method: "POST", 
            headers: { "Content-Type": "application/json", "X-App-Secret": "revolution161" },
            body: JSON.stringify({ contents: [{ parts: [{ text: promptText }] }] })
        });
        const data = await response.json();
        if (data.error) return { error: true };
        return data; 
    } catch (e) { return { error: true }; }
}

const starSpinner = `<svg class="spinner" viewBox="0 0 24 24" width="1.4em" height="1.4em"><path fill="url(#rbGrad)" stroke="var(--color-accent)" stroke-width="0.5" d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>`;
const rbStar = `<svg viewBox="0 0 24 24" width="1.2em" height="1.2em" style="vertical-align: sub; margin-left: 4px;"><path fill="url(#rbGrad)" stroke="#FF0000" stroke-width="0.5" d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>`;

const uiTexte = {
    en: {
        init: "Fetching data...", error: "Error: Could not connect.", btnTranslate: "Translate", btnLoading: "Translating...", btnDone: "Translated",
        btnReadMore: "Original", btnExpand: "Read More ⬇️", btnCollapse: "Collapse ⬆️", filterAll: "All Portals", sortNew: "Newest", sortOld: "Oldest",
        searchRegion: "🌍 Region", searchTopic: "🏷️ Topic", latestNews: "Latest News:", translatingRest: "Translating remaining text...",
        topBookmarks: "Bookmarks", btnDonateTop: "Donate", donateTitle: "Support the Project", 
        donateBody: "This project runs independently. Donations are voluntary.", donateWarning: "⚠️ WARNING: By proceeding, you are leaving the anonymous app environment and will be redirected to PayPal.",
        btnPaypal: "Continue to PayPal", btnDonateCancel: "Close", dateLabel: "DATE:", langLabel: "Translate to:",
        searchPlace: "Search articles...", bookmarkCat: "Saved Bookmarks", btnBookmark: "Bookmark" + rbStar, btnUnbookmark: "Saved" + rbStar,
        themeLabel: "Design:", themeDark: "Dark", themeLight: "Light", clearBtn: "Clear Cache 🗑️",
        catGlobal: "Global", catEurope: "Europe", catAfrica: "Africa", catNorthAmerica: "North Am.", catLatinAmerica: "Latin Am.", catAsia: "Asia", catAustralia: "Australia",
        catLabor: "Labor", catAntifascism: "Antifa", catAntisexism: "Antisexism", catQueer: "Queer", catAntiracism: "Antiracism", catNoBorders: "No Borders", catAnticapitalism: "Anti-Cap", catTheory: "Theory", catAnticolonialism: "Anti-Col", catAntiimperialism: "Anti-Imp", catSquatting: "Housing/Squats", catDemos: "Demos", catAntirepression: "Anti-Rep/Prisons", catCyber: "Cyber", catNoWar: "No War", catAnimal: "Animal Lib", catEco: "Eco-Anarchy", catIndigenous: "Indigenous", catHealth: "Health/Disability", catLibraries: "Libraries",
        fbBtn: "💬 Contact", fbTitle: "Contact", fbPlace: "Write your ideas or bug reports here...", fbCaptcha: "Captcha: What is", fbCancel: "Cancel", fbSend: "Send via Mail", fbErrCap: "Captcha is wrong!", fbErrEmpty: "Please write something first.",
        infoBtn: "ℹ️ Info", infoTitle: "App Info & Security (OPSEC)", archiveTitle: "🗄️ Archive (> 3 Months)", publisherLabel: "SOURCE:", authorLabel: "AUTHOR:", contactLabel: "Contact:",
        infoBody: `<p><strong>Passion Project:</strong> This is an independent, non-commercial passion project. It may contain errors. Please report bugs or broken sources via the "Contact" section.</p><p><strong>Secure Architecture:</strong> This app operates completely without tracking cookies, user accounts, or background logs.</p><p><strong>Content & Aggregation:</strong> This app is a pure RSS feed reader. We do not write or host the articles ourselves.</p><p><strong>AI Translations & Privacy:</strong> Translations are dynamically generated by AI and may contain errors. Your requests are anonymized: absolutely no IP addresses or personal user data are collected or tracked during this process.</p>`
    },
    de: {
        init: "Lade Daten...", error: "Fehler: Keine Verbindung.", btnTranslate: "Übersetzen", btnLoading: "Übersetze...", btnDone: "Übersetzt",
        btnReadMore: "Zum Original", btnExpand: "Weiterlesen ⬇️", btnCollapse: "Zuklappen ⬆️", filterAll: "Alle Quellen", sortNew: "Neueste", sortOld: "Älteste",
        searchRegion: "🌍 Region", searchTopic: "🏷️ Thema", latestNews: "Aktuellste News:", translatingRest: "Übersetze Rest...",
        topBookmarks: "Lesezeichen", btnDonateTop: "Spenden", donateTitle: "Projekt unterstützen", 
        donateBody: "Dieses Projekt läuft unabhängig. Spenden von Unterstützer*innen sind freiwillig.", donateWarning: "⚠️ HINWEIS: Wenn du fortfährst, verlässt du die anonyme App-Umgebung und wirst zu PayPal weitergeleitet.",
        btnPaypal: "Weiter zu PayPal", btnDonateCancel: "Schließen", dateLabel: "DATUM:", langLabel: "Übersetzen in:",
        searchPlace: "Artikel suchen...", bookmarkCat: "Lesezeichen", btnBookmark: "Merken" + rbStar, btnUnbookmark: "Gemerkt" + rbStar,
        themeLabel: "Design:", themeDark: "Dunkel", themeLight: "Hell", clearBtn: "Cache löschen 🗑️",
        catGlobal: "Global", catEurope: "Europa", catAfrica: "Afrika", catNorthAmerica: "Nordam.", catLatinAmerica: "Lateinam.", catAsia: "Asien", catAustralia: "Australien",
        catLabor: "Arbeitskämpfe", catAntifascism: "Antifaschismus", catAntisexism: "Antisexismus", catQueer: "Queer-Feminismus", catAntiracism: "Antirassismus", catNoBorders: "No Borders", catAnticapitalism: "Antikapitalismus", catTheory: "Theorie & Strategie", catAnticolonialism: "Antikolonialismus", catAntiimperialism: "Anti-Imperialismus", catSquatting: "Hausbesetzungen", catDemos: "Demonstrationen", catAntirepression: "Anti-Rep & Knast", catCyber: "Cyber-Aktivismus", catNoWar: "Kriegsdienstverweigerung", catAnimal: "Tierbefreiung", catEco: "Ökologie & Klima", catIndigenous: "Indigene Kämpfe", catHealth: "Radical Health", catLibraries: "Bibliotheken",
        fbBtn: "💬 Kontakt", fbTitle: "Kontakt", fbPlace: "Schreibe hier Ideen, Fehler oder neue Quellen...", fbCaptcha: "Captcha: Was ist", fbCancel: "Abbrechen", fbSend: "Senden (Mail)", fbErrCap: "Captcha ist falsch!", fbErrEmpty: "Bitte schreibe zuerst einen Text.",
        infoBtn: "ℹ️ Info", infoTitle: "App Info & Sicherheit", archiveTitle: "🗄️ Archiv (> 3 Monate)", publisherLabel: "QUELLE:", authorLabel: "AUTOR*IN:", contactLabel: "Kontakt:",
        infoBody: `<p><strong>Aus Leidenschaft:</strong> Dieses Projekt ist ein unabhängiges Leidenschaftsprojekt von und für Aktivist*innen. Bitte melde Bugs oder fehlerhafte Quellen über den Kontakt-Bereich.</p><p><strong>Sichere Architektur (OPSEC):</strong> Diese App arbeitet komplett ohne Tracker-Cookies für die Besucher*innen, Accounts oder Hintergrund-Protokolle.</p><p><strong>Inhalte & Aggregation:</strong> Diese App ist ein reiner RSS-Feed-Reader. Wir als Entwickler*innen schreiben oder hosten die Artikel nicht selbst.</p><p><strong>KI-Übersetzungen & Datenschutz:</strong> Die Übersetzungen werden dynamisch durch eine KI generiert und können Fehler enthalten. Deine Anfragen als Nutzer*in sind komplett anonymisiert: Es werden absolut keine IP-Adressen oder persönlichen Daten gesammelt oder weitergegeben.</p>`
    },
    es: {
        init: "Cargando datos...", error: "Error de conexión.", btnTranslate: "Traducir", btnLoading: "Traduciendo...", btnDone: "Traducido",
        btnReadMore: "Original", btnExpand: "Leer más ⬇️", btnCollapse: "Ocultar ⬆️", filterAll: "Todos los portales", sortNew: "Más nuevos", sortOld: "Más antiguos",
        searchRegion: "🌍 Región", searchTopic: "🏷️ Tema", latestNews: "Últimas noticias:", translatingRest: "Traduciendo el resto...",
        topBookmarks: "Marcadores", btnDonateTop: "Donar", donateTitle: "Apoyar el proyecto", 
        donateBody: "Este proyecto es independiente. Las donaciones son voluntarias.", donateWarning: "⚠️ ADVERTENCIA: Serás redirigido a PayPal.",
        btnPaypal: "Continuar a PayPal", btnDonateCancel: "Cerrar", dateLabel: "FECHA:", langLabel: "Traducir a:",
        searchPlace: "Buscar artículos...", bookmarkCat: "Marcadores guardados", btnBookmark: "Guardar" + rbStar, btnUnbookmark: "Guardado" + rbStar,
        themeLabel: "Diseño:", themeDark: "Oscuro", themeLight: "Claro", clearBtn: "Borrar caché 🗑️",
        catGlobal: "Global", catEurope: "Europa", catAfrica: "África", catNorthAmerica: "Norteamérica", catLatinAmerica: "Latinoamérica", catAsia: "Asia", catAustralia: "Australia",
        catLabor: "Sindicalismo", catAntifascism: "Antifa", catAntisexism: "Antisexismo", catQueer: "Queer", catAntiracism: "Antirracismo", catNoBorders: "Sin Fronteras", catAnticapitalism: "Anticapitalismo", catTheory: "Teoría", catAnticolonialism: "Anticolonialismo", catAntiimperialism: "Antiimperialismo", catSquatting: "Vivienda/Okupas", catDemos: "Manifs", catAntirepression: "Anti-Rep/Prisiones", catCyber: "Cyber", catNoWar: "No War", catAnimal: "Lib. Animal", catEco: "Eco-Anarquía", catIndigenous: "Indígena", catHealth: "Salud Radical", catLibraries: "Bibliotecas",
        fbBtn: "💬 Contacto", fbTitle: "Contacto", fbPlace: "Escribe aquí...", fbCaptcha: "Captcha: Cuánto es", fbCancel: "Cancelar", fbSend: "Enviar", fbErrCap: "¡Captcha incorrecto!", fbErrEmpty: "Escribe algo primero.",
        infoBtn: "ℹ️ Info", infoTitle: "Info y Seguridad", archiveTitle: "🗄️ Archivo (> 3 Meses)", publisherLabel: "FUENTE:", authorLabel: "AUTOR:", contactLabel: "Contacto:",
        infoBody: `<p><strong>Proyecto de Pasión:</strong> Este es un proyecto independiente y no comercial. Puede contener errores. Por favor, reporta fallos a través de "Contacto".</p><p><strong>Arquitectura Segura:</strong> Esta app funciona sin cookies de rastreo ni cuentas de usuario.</p><p><strong>Contenido:</strong> Esta app es un lector de feeds RSS. No escribimos ni alojamos los artículos.</p><p><strong>Privacidad e IA:</strong> Las traducciones son generadas por IA. Sus solicitudes son anonimizadas.</p>`
    },
    fr: {
        init: "Chargement des données...", error: "Erreur de connexion.", btnTranslate: "Traduire", btnLoading: "Traduction...", btnDone: "Traduit",
        btnReadMore: "Original", btnExpand: "Lire la suite ⬇️", btnCollapse: "Réduire ⬆️", filterAll: "Tous les portails", sortNew: "Plus récents", sortOld: "Plus anciens",
        searchRegion: "🌍 Région", searchTopic: "🏷️ Thème", latestNews: "Dernières nouvelles:", translatingRest: "Traduction du reste...",
        topBookmarks: "Signets", btnDonateTop: "Faire un don", donateTitle: "Soutenir le projet", 
        donateBody: "Ce projet est indépendant.", donateWarning: "⚠️ ATTENTION: Vous serez redirigé vers PayPal.",
        btnPaypal: "Continuer vers PayPal", btnDonateCancel: "Fermer", dateLabel: "DATE:", langLabel: "Traduire en:",
        searchPlace: "Rechercher...", bookmarkCat: "Signets enregistrés", btnBookmark: "Sauvegarder" + rbStar, btnUnbookmark: "Sauvegardé" + rbStar,
        themeLabel: "Design:", themeDark: "Sombre", themeLight: "Clair", clearBtn: "Vider le cache 🗑️",
        catGlobal: "Global", catEurope: "Europe", catAfrica: "Afrique", catNorthAmerica: "Am. du Nord", catLatinAmerica: "Am. Latine", catAsia: "Asie", catAustralia: "Australie",
        catLabor: "Syndicalisme", catAntifascism: "Antifa", catAntisexism: "Antisexisme", catQueer: "Queer", catAntiracism: "Antiracisme", catNoBorders: "Sans Frontières", catAnticapitalism: "Anticapitalisme", catTheory: "Théorie", catAnticolonialism: "Anticolonialisme", catAnti-impérialisme: "Anti-Impérialisme", catSquatting: "Logement/Squats", catDemos: "Manifs", catAntirepression: "Anti-Rép/Prisons", catCyber: "Cyber", catNoWar: "No War", catAnimal: "Lib. Animale", catEco: "Éco-Anarchie", catIndigenous: "Indigène", catHealth: "Santé Radicale", catLibraries: "Bibliothèques",
        fbBtn: "💬 Contact", fbTitle: "Contact", fbPlace: "Écrivez ici...", fbCaptcha: "Captcha: Combien font", fbCancel: "Annuler", fbSend: "Envoyer", fbErrCap: "Captcha incorrect!", fbErrEmpty: "Écrivez quelque chose d'abord.",
        infoBtn: "ℹ️ Info", infoTitle: "Info & Sécurité", archiveTitle: "🗄️ Archives (> 3 Mois)", publisherLabel: "SOURCE:", authorLabel: "AUTEUR:", contactLabel: "Contact:",
        infoBody: `<p><strong>Projet de Passion:</strong> Il s'agit d'un projet indépendant. Veuillez signaler les bugs via "Contact".</p><p><strong>Architecture Sécurisée:</strong> Fonctionne sans cookies de suivi ni comptes.</p><p><strong>Contenido:</strong> C'est un lecteur de flux RSS. Nous n'écrivons pas les articles.</p><p><strong>Confidentialité et IA:</strong> Les traductions de l'IA sont traitées de manière anonyme.</p>`
    },
    it: {
        init: "Caricamento dati...", error: "Errore di connessione.", btnTranslate: "Traduci", btnLoading: "Traduzione...", btnDone: "Tradotto",
        btnReadMore: "Originale", btnExpand: "Leggi di più ⬇️", btnCollapse: "Riduci ⬆️", filterAll: "Tutti i portali", sortNew: "Più recenti", sortOld: "Più vecchi",
        searchRegion: "🌍 Regione", searchTopic: "🏷️ Tema", latestNews: "Ultime notizie:", translatingRest: "Traduzione in corso...",
        topBookmarks: "Segnalibri", btnDonateTop: "Dona", donateTitle: "Sostieni il progetto", 
        donateBody: "Questo progetto è indipendente.", donateWarning: "⚠️ ATTENZIONE: Verrai reindirizzato a PayPal.",
        btnPaypal: "Continua su PayPal", btnDonateCancel: "Chiudi", dateLabel: "DATA:", langLabel: "Traduci in:",
        searchPlace: "Cerca articoli...", bookmarkCat: "Segnalibri salvati", btnBookmark: "Salva" + rbStar, btnUnbookmark: "Salvato" + rbStar,
        themeLabel: "Design:", themeDark: "Scuro", themeLight: "Chiaro", clearBtn: "Svuota cache 🗑️",
        catGlobal: "Globale", catEurope: "Europa", catAfrica: "Africa", catNorthAmerica: "Nord America", catLatinAmerica: "America Latina", catAsia: "Asia", catAustralia: "Australia",
        catLabor: "Lotte sul Lavoro", catAntifascism: "Antifa", catAntisexism: "Antisessismo", catQueer: "Queer", catAntiracism: "Antirazzismo", catNoBorders: "No Borders", catAnticapitalism: "Anticapitalismo", catTheory: "Teoria", catAnticolonialism: "Anticolonialismo", catAntiimperialism: "Anti-Imperialismo", catSquatting: "Casa/Occupazioni", catDemos: "Manifestazioni", catAntirepression: "Anti-Rep/Carceri", catCyber: "Cyber", catNoWar: "No War", catAnimal: "Lib. Animale", catEco: "Eco-Anarchia", catIndigenous: "Indigeno", catHealth: "Salute Radicale", catLibraries: "Biblioteche",
        fbBtn: "💬 Contatto", fbTitle: "Contatto", fbPlace: "Scrivi qui...", fbCaptcha: "Captcha: Quanto fa", fbCancel: "Annulla", fbSend: "Invia", fbErrCap: "Captcha errato!", fbErrEmpty: "Scrivi qualcosa prima.",
        infoBtn: "ℹ️ Info", infoTitle: "Info & Sicurezza", archiveTitle: "🗄️ Archivio (> 3 Mesi)", publisherLabel: "FONTE:", authorLabel: "AUTORE:", contactLabel: "Contatto:",
        infoBody: `<p><strong>Progetto di Passione:</strong> Progetto indipendente. Segnala i bug tramite "Contatto".</p><p><strong>Architettura Sicura:</strong> Funziona senza cookie o account.</p>`
    },
    pt: {
        init: "Carregando dados...", error: "Erro: Sem conexão.", btnTranslate: "Traduzir", btnLoading: "Traduzindo...", btnDone: "Traduzido",
        btnReadMore: "Original", btnExpand: "Ler mais ⬇️", btnCollapse: "Reduzir ⬆️", filterAll: "Todos os portais", sortNew: "Mais recentes", sortOld: "Mais antigos",
        searchRegion: "🌍 Região", searchTopic: "🏷️ Tema", latestNews: "Últimas notícias:", translatingRest: "Traduzindo o resto...",
        topBookmarks: "Marcadores", btnDonateTop: "Doar", donateTitle: "Apoiar o projeto",
        donateBody: "Este projeto é independente. As doações são voluntárias.", donateWarning: "⚠️ AVISO: Você será redirecionado para o PayPal.",
        btnPaypal: "Continuar para PayPal", btnDonateCancel: "Fechar", dateLabel: "DATA:", langLabel: "Traduzir para:",
        searchPlace: "Buscar artigos...", bookmarkCat: "Marcadores salvos", btnBookmark: "Salvar" + rbStar, btnUnbookmark: "Salvo" + rbStar,
        themeLabel: "Design:", themeDark: "Escuro", themeLight: "Claro", clearBtn: "Limpar Cache 🗑️",
        catGlobal: "Global", catEurope: "Europa", catAfrica: "África", catNorthAmerica: "Am. do Norte", catLatinAmerica: "Am. Latina", catAsia: "Ásia", catAustralia: "Austrália",
        catLabor: "Trabalho", catAntifascism: "Antifa", catAntisexism: "Antissexismo", catQueer: "Queer", catAntiracism: "Antirracismo", catNoBorders: "Sem Fronteiras", catAnticapitalism: "Anticapitalismo", catTheory: "Teoria", catAnticolonialism: "Anticolonialismo", catAntiimperialism: "Anti-Imp", catSquatting: "Ocupações", catDemos: "Manifestações", catAntirepression: "Antirrep./Prisões", catCyber: "Ciber", catNoWar: "Sem Guerra", catAnimal: "Lib. Animal", catEco: "Eco-Anarquia", catIndigenous: "Indígena", catHealth: "Saúde Radical", catLibraries: "Bibliotecas",
        fbBtn: "💬 Contato", fbTitle: "Contato", fbPlace: "Escreva aqui suas ideias ou bugs...", fbCaptcha: "Captcha: Quanto é", fbCancel: "Cancelar", fbSend: "Enviar (Email)", fbErrCap: "Captcha incorreto!", fbErrEmpty: "Escreva algo primeiro.",
        infoBtn: "ℹ️ Info", infoTitle: "App Info & Segurança", archiveTitle: "🗄️ Arquivo (> 3 Meses)", publisherLabel: "FONTE:", authorLabel: "AUTOR:", contactLabel: "Contato:",
        infoBody: `<p><strong>Projeto de Paixão:</strong> Este é um projeto independente. Relate bugs na seção "Contato".</p><p><strong>Arquitetura Segura:</strong> Este app funciona sem cookies de rastreamento ou contas.</p>`
    },
    ru: {
        init: "Загрузка данных...", error: "Ошибка подключения.", btnTranslate: "Перевести", btnLoading: "Перевод...", btnDone: "Переведено",
        btnReadMore: "Оригинал", btnExpand: "Читать далее ⬇️", btnCollapse: "Свернуть ⬆️", filterAll: "Все порталы", sortNew: "Сначала новые", sortOld: "Сначала старые",
        searchRegion: "🌍 Регион", searchTopic: "🏷️ Тема", latestNews: "Последние новости:", translatingRest: "Перевод остального текста...",
        topBookmarks: "Закладки", btnDonateTop: "Донат", donateTitle: "Поддержать проект",
        donateBody: "Этот проект независимый. Пожертвования добровольны.", donateWarning: "⚠️ ВНИМАНИЕ: Вы будете перенаправлены на PayPal.",
        btnPaypal: "Перейти к PayPal", btnDonateCancel: "Закрыть", dateLabel: "ДАТА:", langLabel: "Перевести на:",
        searchPlace: "Поиск статей...", bookmarkCat: "Сохраненные закладки", btnBookmark: "Сохранить" + rbStar, btnUnbookmark: "Сохранено" + rbStar,
        themeLabel: "Дизайн:", themeDark: "Темный", themeLight: "Светлый", clearBtn: "Очистить кэш 🗑️",
        catGlobal: "Мир", catEurope: "Европа", catAfrica: "Африка", catNorthAmerica: "Сев. Америка", catLatinAmerica: "Лат. Америка", catAsia: "Азия", catAustralia: "Австралия",
        catLabor: "Труд", catAntifascism: "Антифа", catAntisexism: "Антисексизм", catQueer: "Квир", catAntiracism: "Антирасизм", catNoBorders: "Без границ", catAnticapitalism: "Антикапитализм", catTheory: "Теория", catAnticolonialism: "Антиколониализм", catAntiimperialism: "Антиимпериализм", catSquatting: "Сквоты", catDemos: "Акции", catAntirepression: "Антирепрессии/Тюрьмы", catCyber: "Кибер", catNoWar: "Нет войне", catAnimal: "Осв. животных", catEco: "Эко-анархия", catIndigenous: "Коренные народы", catHealth: "Здоровье", catLibraries: "Библиотеки",
        fbBtn: "💬 Контакт", fbTitle: "Контакт", fbPlace: "Напишите ваши идеи или ошибки здесь...", fbCaptcha: "Капча: Сколько будет", fbCancel: "Отмена", fbSend: "Отправить (Почта)", fbErrCap: "Неверная капча!", fbErrEmpty: "Сначала напишите что-нибудь.",
        infoBtn: "ℹ️ Инфо", infoTitle: "Инфо и безопасность", archiveTitle: "🗄️ Архив (> 3 Месяцев)", publisherLabel: "ИСТОЧНИК:", authorLabel: "АВТОР:", contactLabel: "Контакт:",
        infoBody: `<p><strong>Проект для души:</strong> Это независимый проект.</p>`
    },
    el: {
        init: "Φόρτωση δεδομένων...", error: "Σφάλμα σύνδεσης.", btnTranslate: "Μετάφραση", btnLoading: "Μετάφραση...", btnDone: "Μεταφράστηκε",
        btnReadMore: "Πρωτότυπο", btnExpand: "Περισσότερα ⬇️", btnCollapse: "Λιγότερα ⬆️", filterAll: "Όλες οι πηγές", sortNew: "Νεότερα", sortOld: "Παλαιότερα",
        searchRegion: "🌍 Περιοχή", searchTopic: "🏷️ Θέμα", latestNews: "Τελευταία Νέα:", translatingRest: "Μετάφραση υπολοίπου...",
        topBookmarks: "Αποθηκευμένα", btnDonateTop: "Δωρεά", donateTitle: "Υποστήριξη Έργου",
        donateBody: "Αυτό το έργο είναι ανεξάρτητο.", donateWarning: "⚠️ ΠΡΟΕΙΔΟΠΟΙΗΣΗ: Θα μεταφερθείτε στο PayPal.",
        btnPaypal: "Συνέχεια στο PayPal", btnDonateCancel: "Κλείσιμο", dateLabel: "ΗΜΕΡΟΜΗΝΙΑ:", langLabel: "Μετάφραση σε:",
        searchPlace: "Αναζήτηση άρθρων...", bookmarkCat: "Αποθηκευμένα", btnBookmark: "Αποθήκευση" + rbStar, btnUnbookmark: "Αποθηκεύτηκε" + rbStar,
        themeLabel: "Σχεδιασμός:", themeDark: "Σκοτεινό", themeLight: "Φωτεινό", clearBtn: "Εκκαθάριση Cache 🗑️",
        catGlobal: "Παγκόσμια", catEurope: "Ευρώπη", catAfrica: "Αφρική", catNorthAmerica: "Β. Αμερική", catLatinAmerica: "Λατ. Αμερική", catAsia: "Ασία", catAustralia: "Αυστραλία",
        catLabor: "Εργατικά", catAntifascism: "Antifa", catAntisexism: "Αντισεξισμός", catQueer: "Queer", catAntiracism: "Αντιρατσισμός", catNoBorders: "No Borders", catAnticapitalism: "Αντικαπιταλισμός", catTheory: "Θεωρία", catAnticolonialism: "Αντιαποικιοκρατία", catAntiimperialism: "Αντιιμπεριαλισμός", catSquatting: "Καταλήψεις", catDemos: "Διαδηλώσεις", catAntirepression: "Αντικαταστολή/Φυλακές", catCyber: "Κυβερνο", catNoWar: "Όχι Πόλεμος", catAnimal: "Απελ. Ζώων", catEco: "Οικο-Αναρχία", catIndigenous: "Ιθαγενείς", catHealth: "Υγεία", catLibraries: "Βιβλιοθήκες",
        fbBtn: "💬 Επικοινωνία", fbTitle: "Επικοινωνία", fbPlace: "Γράψτε εδώ τις ιδέες ή τα σφάλματα...", fbCaptcha: "Captcha: Πόσο κάνει", fbCancel: "Ακύρωση", fbSend: "Αποστολή (Mail)", fbErrCap: "Λάθος Captcha!", fbErrEmpty: "Γράψτε κάτι πρώτα.",
        infoBtn: "ℹ️ Info", infoTitle: "Πληροφορίες & Ασφάλεια", archiveTitle: "🗄️ Αρχείο (> 3 Μήνες)", publisherLabel: "ΠΗΓΗ:", authorLabel: "ΣΥΓΓΡΑΦΕΑΣ:", contactLabel: "Επικοινωνία:",
        infoBody: `<p><strong>Έργο Πάθους:</strong> Αυτό είναι ένα ανεξάρτητο έργο.</p>`
    },
    tr: {
        init: "Veriler yükleniyor...", error: "Bağlantı hatası.", btnTranslate: "Çevir", btnLoading: "Çevriliyor...", btnDone: "Çevrildi",
        btnReadMore: "Orijinal", btnExpand: "Devamını Oku ⬇️", btnCollapse: "Daralt ⬆️", filterAll: "Tüm Portallar", sortNew: "En Yeni", sortOld: "En Eski",
        searchRegion: "🌍 Bölge", searchTopic: "🏷️ Konu", latestNews: "Son Haberler:", translatingRest: "Kalanı çevriliyor...",
        topBookmarks: "Kaydedilenler", btnDonateTop: "Bağış", donateTitle: "Projeyi Destekle",
        donateBody: "Bu proje bağımsızdır.", donateWarning: "⚠️ UYARI: PayPal'a yönlendirileceksiniz.",
        btnPaypal: "PayPal'a Devam Et", btnDonateCancel: "Kapat", dateLabel: "TARİH:", langLabel: "Şuna çevir:",
        searchPlace: "Makale ara...", bookmarkCat: "Kaydedilenler", btnBookmark: "Kaydet" + rbStar, btnUnbookmark: "Kaydedildi" + rbStar,
        themeLabel: "Tasarım:", themeDark: "Koyu", themeLight: "Açık", clearBtn: "Önbelleği Temizle 🗑️",
        catGlobal: "Küresel", catEurope: "Avrupa", catAfrica: "Afrika", catNorthAmerica: "K. Amerika", catLatinAmerica: "Lat. Amerika", catAsia: "Asya", catAustralia: "Avustralya",
        catLabor: "Emek", catAntifascism: "Antifa", catAntisexism: "Antiseksizm", catQueer: "Kuir", catAntiracism: "Irkçılık Karşıtı", catNoBorders: "Sınırsız", catAnticapitalism: "Antikapitalizm", catTheory: "Teori", catAnticolonialism: "Sömürgecilik Karşıtı", catAntiimperialism: "Anti-Emperyalizm", catSquatting: "İşgal/Barınma", catDemos: "Eylemler", catAntirepression: "Baskı Karşıtı/Zindanlar", catCyber: "Siber", catNoWar: "Savaşa Hayır", catAnimal: "Hayvan Özgürlüğü", catEco: "Eko-Anarşi", catIndigenous: "Yerli Halklar", catHealth: "Sağlık", catLibraries: "Kütüphaneler",
        fbBtn: "💬 İletişim", fbTitle: "İletişim", fbPlace: "Fikirlerinizi veya hataları buraya yazın...", fbCaptcha: "Captcha: Kaç eder", fbCancel: "İptal", fbSend: "Gönder (Mail)", fbErrCap: "Yanlış Captcha!", fbErrEmpty: "Lütfen önce bir şeyler yazın.",
        infoBtn: "ℹ️ Bilgi", infoTitle: "Uygulama Bilgisi & Güvenlik", archiveTitle: "🗄️ Arşiv (> 3 Ay)", publisherLabel: "KAYNAK:", authorLabel: "YAZAR:", contactLabel: "İletişim:",
        infoBody: `<p><strong>Tutku Projesi:</strong> Bu bağımsız bir projedir.</p>`
    }
};

let currentLang = "en";
let activeKontinent = "Global"; 
let allNewsData = []; 
let currentKontinentData = []; 
let currentSourceFilter = "ALL"; 

function setTxt(id, text) { const e = document.getElementById(id); if (e && text) e.innerText = text; }
function setHtml(id, html) { const e = document.getElementById(id); if (e && html) e.innerHTML = html; }
function setPh(id, text) { const e = document.getElementById(id); if (e && text) e.placeholder = text; }

function changeTheme(themeName) {
    const body = document.getElementById('app-body');
    if(body) {
        body.classList.remove('theme-dark', 'theme-light');
        body.classList.add(themeName);
        localStorage.setItem('wrn_theme_style', themeName);
    }
}

function clearAllData() {
    const confirmTxt = currentLang === "de" ? "Möchtest du wirklich alle Lesezeichen, den Gelesen-Verlauf und alle Einstellungen restlos löschen?" : "Do you really want to completely clear all bookmarks, read history, and local settings?";
    if (confirm(confirmTxt)) { localStorage.clear(); window.location.reload(); }
}

function changeLanguage() {
    const langSelect = document.getElementById('ui-language');
    if(langSelect) { currentLang = langSelect.value; }
    localStorage.setItem('wrn_system_lang', currentLang); 
    
    const t = uiTexte[currentLang] || uiTexte['en'];
    
    setTxt('txt-lang-label', t.langLabel);
    setTxt('txt-theme-label', t.themeLabel);
    setTxt('opt-theme-dark', t.themeDark);
    setTxt('opt-theme-light', t.themeLight);
    setTxt('btn-clear-cache', t.clearBtn);
    setTxt('txt-region-summary', t.searchRegion);
    setTxt('txt-topic-summary', t.searchTopic);
    setTxt('txt-archive-title', t.archiveTitle);
    setTxt('txt-contact-label', t.contactLabel);
    
    setTxt('opt-sort-new', t.sortNew);
    setTxt('opt-sort-old', t.sortOld);
    
    setTxt('txt-top-bookmarks', t.topBookmarks);
    setTxt('txt-donate-btn', t.btnDonateTop);
    setTxt('txt-donate-title', t.donateTitle);
    setTxt('txt-donate-body', t.donateBody);
    setTxt('txt-donate-warning', t.donateWarning);
    setTxt('btn-paypal', t.btnPaypal);
    setTxt('btn-donate-cancel', t.btnDonateCancel);
    setPh('search-input', t.searchPlace);
    
    setTxt('btn-glob', t.catGlobal); setTxt('btn-eur', t.catEurope); setTxt('btn-afr', t.catAfrica);
    setTxt('btn-nam', t.catNorthAmerica); setTxt('btn-lam', t.catLatinAmerica); setTxt('btn-asi', t.catAsia); setTxt('btn-aus', t.catAustralia);
    
    setTxt('cat-labor', t.catLabor); setTxt('cat-antifascism', t.catAntifascism); setTxt('cat-antisexism', t.catAntisexism);
    setTxt('cat-queer', t.catQueer); setTxt('cat-antiracism', t.catAntiracism); setTxt('cat-noborders', t.catNoBorders);
    setTxt('cat-anticapitalism', t.catAnticapitalism); setTxt('cat-theory', t.catTheory); setTxt('cat-anticolonialism', t.catAnticolonialism);
    setTxt('cat-antiimperialism', t.catAntiimperialism); setTxt('cat-squatting', t.catSquatting); setTxt('cat-demos', t.catDemos);
    setTxt('cat-antirepression', t.catAntirepression); setTxt('cat-cyber', t.catCyber); setTxt('cat-nowar', t.catNoWar);
    setTxt('cat-animal', t.catAnimal); setTxt('cat-eco', t.catEco); setTxt('cat-indigenous', t.catIndigenous);
    setTxt('cat-health', t.catHealth); setTxt('btn-lib', t.catLibraries); 

    setTxt('btn-open-info', "ℹ️ " + t.infoBtn);
    setTxt('txt-info-title', t.infoTitle);
    setHtml('txt-info-body', t.infoBody);
    
    setTxt('btn-open-feedback', t.fbBtn);
    setTxt('txt-fb-title', t.fbTitle);
    setPh('fb-text', t.fbPlace);
    setTxt('txt-captcha-q', t.fbCaptcha);
    setTxt('btn-fb-cancel', t.fbCancel);
    setTxt('btn-fb-send', t.fbSend);
    
    if(activeKontinent === "Bookmarks") { ladeBookmarks(); } else if (currentKontinentData.length > 0) { setTxt('status-container', t.latestNews); applyFilters(); }
}

function getSavedBookmarks() { return JSON.parse(localStorage.getItem('wrn_bookmarks') || '[]'); }
function getReadArticles() { return JSON.parse(localStorage.getItem('wrn_read_list') || '[]'); }

function markAsRead(link, index) {
    let readList = getReadArticles();
    if (!readList.includes(link)) { readList.push(link); localStorage.setItem('wrn_read_list', JSON.stringify(readList)); }
    const card = document.getElementById(`card-${index}`); if(card) card.classList.add('read');
}

function toggleBookmark(index) {
    let bookmarks = getSavedBookmarks(); let article = currentKontinentData[index];
    let existingIdx = bookmarks.findIndex(b => b.link === article.link);
    const t = uiTexte[currentLang] || uiTexte['en'];

    if (existingIdx > -1) { bookmarks.splice(existingIdx, 1); setHtml(`bmark-${index}`, t.btnBookmark); } 
    else { bookmarks.push(article); setHtml(`bmark-${index}`, t.btnUnbookmark); }
    
    localStorage.setItem('wrn_bookmarks', JSON.stringify(bookmarks));
    if(activeKontinent === "Bookmarks") ladeBookmarks();
}

function ladeBookmarks() {
    if (activeKontinent === "Bookmarks") { ladeKontinentNews('Global'); return; }

    activeKontinent = "Bookmarks"; currentKontinentData = getSavedBookmarks();
    currentSourceFilter = "ALL"; 
    document.querySelectorAll('.btn-nav').forEach(btn => btn.classList.remove('active'));
    const bBtn = document.getElementById('btn-bookmarks'); if(bBtn) bBtn.classList.add('active');
    
    const t = uiTexte[currentLang] || uiTexte['en'];
    setTxt('status-container', t.bookmarkCat + ` (${currentKontinentData.length})`);
    applyFilters();
}

function openDonate() { const ov = document.getElementById('fb-overlay'); if(ov) ov.style.display = 'block'; const md = document.getElementById('donate-modal'); if(md) md.style.display = 'block'; }

function openFeedback() {
    const ov = document.getElementById('fb-overlay'); if(ov) ov.style.display = 'block'; const md = document.getElementById('fb-modal'); if(md) md.style.display = 'block';
    capVal1 = Math.floor(Math.random() * 10) + 1; capVal2 = Math.floor(Math.random() * 10) + 1;
    setTxt('captcha-num1', capVal1); setTxt('captcha-num2', capVal2);
    const ca = document.getElementById('captcha-answer'); if(ca) ca.value = ''; const ft = document.getElementById('fb-text'); if(ft) ft.value = '';
}

function openInfo() { const ov = document.getElementById('fb-overlay'); if(ov) ov.style.display = 'block'; const md = document.getElementById('info-modal'); if(md) md.style.display = 'block'; }

function closeAllModals() { 
    const ov = document.getElementById('fb-overlay'); if(ov) ov.style.display = 'none'; 
    const m1 = document.getElementById('fb-modal'); if(m1) m1.style.display = 'none'; 
    const m2 = document.getElementById('info-modal'); if(m2) m2.style.display = 'none'; 
    const m3 = document.getElementById('donate-modal'); if(m3) m3.style.display = 'none'; 
    const m4 = document.getElementById('sources-modal'); if(m4) m4.style.display = 'none'; 
}

function submitFeedback() {
    const ca = document.getElementById('captcha-answer'); const ft = document.getElementById('fb-text'); if(!ca || !ft) return;
    const userAnswer = parseInt(ca.value); const text = ft.value.trim(); const t = uiTexte[currentLang] || uiTexte['en'];
    
    if (text === "") { alert(t.fbErrEmpty); return; }
    if (userAnswer !== (capVal1 + capVal2)) { alert(t.fbErrCap); return; }
    window.location.href = `mailto:worldrevnews@brief.li?subject=Contact&body=${encodeURIComponent(text)}`; closeAllModals();
}

function openSourcesModal() {
    const ov = document.getElementById('fb-overlay'); if(ov) ov.style.display = 'block'; 
    const md = document.getElementById('sources-modal'); if(md) md.style.display = 'block';
    const listContainer = document.getElementById('sources-list-container'); listContainer.innerHTML = '';
    const t = uiTexte[currentLang] || uiTexte['en'];
    
    let html = `<button class="btn-micro" style="width:100%; text-align: left; padding: 10px; font-size: 0.8rem; justify-content: flex-start; border-color: var(--color-green); color: var(--color-green);" onclick="filterBySource('ALL')">🌍 ${t.filterAll}</button>`;
    
    const portals = [...new Set(currentKontinentData.map(item => item.quelleName))].sort();
    portals.forEach(portal => { 
        let isActive = (currentSourceFilter === portal) ? 'background: rgba(0, 240, 255, 0.2); border-color: var(--color-cyan); color: var(--text-main);' : '';
        html += `<button class="btn-micro" style="width:100%; text-align: left; padding: 10px; font-size: 0.8rem; justify-content: flex-start; ${isActive}" onclick="filterBySource('${portal.replace(/'/g, "\\'")}')">${portal}</button>`; 
    });
    listContainer.innerHTML = html;
}

function filterBySource(sourceName) {
    currentSourceFilter = sourceName;
    closeAllModals();
    applyFilters();
}

// FIX: Zwingt die App, beim Start sofort "Global" zu laden.
async function initialisiereApp() {
    const t = uiTexte[currentLang] || uiTexte['en'];
    setTxt('status-container', t.init);
    try {
        const res = await fetch(GITHUB_JSON_URL + "?v=" + new Date().getTime());
        if (!res.ok) throw new Error("Netzwerkfehler");
        
        const fetchedData = await res.json();
        if(fetchedData && fetchedData.length > 0) {
            allNewsData = fetchedData;
            localStorage.setItem('cached_news_data', JSON.stringify(allNewsData));
            ladeKontinentNews("Global");
        } else {
            throw new Error("Leere Daten empfangen");
        }
    } catch (err) {
        try {
            const offlineData = localStorage.getItem('cached_news_data');
            if (offlineData && offlineData.length > 10) {
                allNewsData = JSON.parse(offlineData);
                setTxt('status-container', "[ OFFLINE MODE ]");
                ladeKontinentNews("Global");
            } else {
                setTxt('status-container', t.error);
            }
        } catch(e) { setTxt('status-container', "Fehler: " + e.message); }
    }
}

function ladeKontinentNews(kontinent) {
    if(kontinent === "Bookmarks") return ladeBookmarks();
    activeKontinent = kontinent; currentKontinentData = allNewsData.filter(item => item.kontinent === kontinent);
    currentSourceFilter = "ALL"; 
    
    document.querySelectorAll('.btn-nav').forEach(btn => btn.classList.remove('active'));
    
    const btnMap = { 
        'Global': 'btn-glob', 'Europe': 'btn-eur', 'Africa': 'btn-afr', 'North America': 'btn-nam', 'Latin America': 'btn-lam', 'Asia': 'btn-asi', 'Australia & NZ': 'btn-aus', 
        'Labor Struggles': 'cat-labor', 'Antifascism': 'cat-antifascism', 'Antisexism': 'cat-antisexism', 'Queer-Feminism': 'cat-queer', 'Antiracism': 'cat-antiracism', 'No Borders': 'cat-noborders',
        'Anticapitalism': 'cat-anticapitalism', 'Theory & Strategy': 'cat-theory', 'Anticolonialism': 'cat-anticolonialism', 'Anti-Imperialism': 'cat-antiimperialism', 'Squatting & Housing': 'cat-squatting',
        'Demonstrations': 'cat-demos', 'Anti-Rep & Prisons': 'cat-antirepression', 'Cyberactivism': 'cat-cyber', 'No War': 'cat-nowar', 'Animal Liberation': 'cat-animal', 'Eco-Anarchism': 'cat-eco', 'Indigenous Struggles': 'cat-indigenous',
        'Radical Health & Disability': 'cat-health', 'Libraries': 'btn-lib' 
    };
    
    if(btnMap[kontinent]) { const b = document.getElementById(btnMap[kontinent]); if(b) b.classList.add('active'); }

    const t = uiTexte[currentLang] || uiTexte['en']; setTxt('status-container', t.latestNews);
    applyFilters();
}

function applyFilters() {
    const iSel = document.getElementById('search-input');
    const selPortal = currentSourceFilter || "ALL"; 
    const searchQuery = iSel ? iSel.value.toLowerCase().trim() : "";
    const sortOrder = document.getElementById('sort-select') ? document.getElementById('sort-select').value : "new";
    
    let filtered = (selPortal === "ALL") ? currentKontinentData : currentKontinentData.filter(a => a.quelleName === selPortal);
    if (searchQuery !== "") { filtered = filtered.filter(a => (a.title && a.title.toLowerCase().includes(searchQuery)) || (a.content && a.content.toLowerCase().includes(searchQuery))); }

    filtered.sort((a, b) => {
        let da = 0; let db = 0;
        if(a.pubDate) da = new Date(a.pubDate).getTime(); if(b.pubDate) db = new Date(b.pubDate).getTime();
        
        if (sortOrder === "old") {
            return (isNaN(da) ? 0 : da) - (isNaN(db) ? 0 : db); 
        } else {
            return (isNaN(db) ? 0 : db) - (isNaN(da) ? 0 : da); 
        }
    });
    displayArticles(filtered);
}

// FIX: Textfarbe im Hell-Modus angepasst.
function displayArticles(items) {
    const container = document.getElementById('feed-container'); const archiveContainer = document.getElementById('archive-container'); const archiveTitle = document.getElementById('txt-archive-title');
    if(!container || !archiveContainer) return;
    container.innerHTML = ""; archiveContainer.innerHTML = ""; let archiveCount = 0;
    
    const t = uiTexte[currentLang] || uiTexte['en'];
    let bookmarks = getSavedBookmarks(); let readList = getReadArticles();
    const today = new Date(); const ninetyDaysMs = 90 * 24 * 60 * 60 * 1000;
    
    items.forEach((item, index) => {
        let formatDatum = "LIVE"; let isOld = false;
        try {
            if (item.pubDate) {
                const articleDate = new Date(item.pubDate);
                if (!isNaN(articleDate.getTime())) {
                    formatDatum = articleDate.toISOString().substring(0, 10);
                    if ((today - articleDate) > ninetyDaysMs) { isOld = true; }
                }
            }
        } catch(e) {}

        const fullText = item.content || "Text not available.";
        let teaserText = fullText.substring(0, 100) + "...";
        try { const sentenceMatch = fullText.match(/[^.!?]+[.!?]+/); if(sentenceMatch) teaserText = sentenceMatch[0]; } catch(e) {}
        const imgHtml = item.image ? `<img src="${item.image}" class="article-img" style="display:block;" loading="lazy">` : '';

        let isSaved = bookmarks.some(b => b.link === item.link); let bookmarkTxt = isSaved ? t.btnUnbookmark : t.btnBookmark;
        let isReadClass = readList.includes(item.link) ? "read" : "";

        let publisherName = item.quelleName ? item.quelleName.trim() : "Unbekannte Quelle";
        let authorName = item.author ? item.author.trim() : "";
        
        let metaHtml = `<span class="meta-label">${t.publisherLabel}</span> <span style="color:var(--text-main);">${publisherName}</span> <br>`;
        if (authorName !== "" && authorName.toLowerCase() !== "unknown" && authorName.toLowerCase() !== publisherName.toLowerCase()) {
            metaHtml += `<span class="meta-label">${t.authorLabel}</span> <span style="color:var(--text-main);">${authorName}</span> <br>`;
        }
        metaHtml += `<span class="meta-label">${t.dateLabel}</span> <span style="color:var(--text-main);">${formatDatum}</span>`;

        let articleHTML = `
            <div class="card ${isReadClass}" id="card-${index}" data-translated="none">
                <div class="meta">${metaHtml}</div>
                <div class="title" id="title-${index}">${item.title || 'No Title'}</div>
                ${imgHtml}
                <div class="teaser" id="teaser-${index}">${teaserText}</div>
                <div class="full-content" id="content-${index}">${fullText}</div>
                <div class="button-row">
                    <button class="btn-expand" id="expand-${index}" onclick="toggleArticle(${index})">${t.btnExpand}</button>
                    <button class="btn-translate" id="btn-${index}" onclick="translateArticle(${index})"><span>[ ${t.btnTranslate} ]</span></button>
                    <button class="btn-translate" style="border-color: #B026FF; color: #B026FF;" id="bmark-${index}" onclick="toggleBookmark(${index})">${bookmarkTxt}</button>
                    <button class="btn-translate" style="border-color: var(--color-cyan); color: var(--color-cyan);" onclick="shareArticle('${btoa(unescape(encodeURIComponent(item.title || '')))}', '${btoa(unescape(encodeURIComponent(item.link || '')))}')">[ SHARE 🔗 ]</button>
                    <a href="${item.link || '#'}" target="_blank" style="text-decoration: none;" onclick="markAsRead('${item.link || ''}', ${index})">
                        <button class="btn-translate" style="border-color: var(--color-accent); color: var(--color-accent);">[ ${t.btnReadMore} ]</button>
                    </a>
                </div>
            </div>
        `;

        if (isOld) { archiveContainer.innerHTML += articleHTML; archiveCount++; } else { container.innerHTML += articleHTML; }
    });

    if (archiveTitle) { if (archiveCount > 0) { archiveTitle.style.display = "block"; } else { archiveTitle.style.display = "none"; } }
}

function shareArticle(encodedTitle, encodedLink) {
    try {
        const title = decodeURIComponent(escape(atob(encodedTitle))); const link = decodeURIComponent(escape(atob(encodedLink)));
        if (navigator.share) { navigator.share({ title: title, url: link }).catch(console.error); } 
        else { navigator.clipboard.writeText(title + " - " + link); alert("Link copied to clipboard!"); }
    } catch(e) {}
}

async function toggleArticle(index) {
    const teaser = document.getElementById(`teaser-${index}`); 
    const fullContent = document.getElementById(`content-${index}`);
    const btn = document.getElementById(`expand-${index}`); 
    const card = document.getElementById(`card-${index}`);
    if(!teaser || !fullContent || !btn || !card) return;
    const t = uiTexte[currentLang] || uiTexte['en'];

    try { markAsRead(currentKontinentData[index].link, index); } catch(e){}

    if (card.dataset.expanded === "true") {
        teaser.style.display = "block";
        fullContent.style.display = "none";
        btn.innerText = t.btnExpand;
        card.dataset.expanded = "false";
    } else {
        teaser.style.display = "none";
        fullContent.style.display = "block";
        btn.innerText = t.btnCollapse;
        card.dataset.expanded = "true";
    }
}

async function translateArticle(index) {
    const titleEl = document.getElementById('title-' + index); const teaserEl = document.getElementById('teaser-' + index);
    const contentEl = document.getElementById('content-' + index); const btnEl = document.getElementById('btn-' + index); const card = document.getElementById('card-' + index);
    if(!titleEl || !teaserEl || !contentEl || !btnEl || !card) return;
    const t = uiTexte[currentLang] || uiTexte['en'];

    if(card.dataset.translated === "full" || card.dataset.translated === "translating") return;
    try { markAsRead(currentKontinentData[index].link, index); } catch(e){}

    btnEl.innerHTML = `${starSpinner} <span style="margin-left: 8px;">[ ${t.btnLoading} ]</span>`;
    
    let zielSprache = "English"; const sel = document.getElementById('ui-language');
    if(sel && sel.options[sel.selectedIndex]) zielSprache = sel.options[sel.selectedIndex].text;
    const isExpanded = (contentEl.style.display === "block");
    let genderInstruction = (zielSprache === "Deutsch") ? " Achte bei der deutschen Übersetzung unbedingt auf geschlechtergerechte Sprache (Gendern mit Sternchen, z.B. Aktivist*innen)." : "";
    
    let promptText = isExpanded ? 
        `Translate title and text fluently into ${zielSprache}.${genderInstruction} Separate with "---". \n\nTitle: ${titleEl.innerText}\n\nText: ${contentEl.innerText}` :
        `Translate title and text fluently into ${zielSprache}.${genderInstruction} Separate with "---". \n\nTitle: ${titleEl.innerText}\n\nText: ${teaserEl.innerText}`;

    const data = await fetchFromGemini(promptText);
    if (data.error) { btnEl.innerHTML = "[ ERROR ]"; return; }

    const parts = data.candidates[0].content.parts[0].text.split("---");
    let transTitle = parts.length >= 2 ? parts[0].trim() : "";
    let transText = parts.length >= 2 ? parts[1].trim() : data.candidates[0].content.parts[0].text.trim();

    if (isExpanded) { if(transTitle) titleEl.innerText = transTitle; contentEl.innerText = transText; card.dataset.translated = "full"; } 
    else { if(transTitle) titleEl.innerText = transTitle; teaserEl.innerText = transText; card.dataset.translated = "teaser"; }
    titleEl.classList.add('translated'); btnEl.innerHTML = `[ ${t.btnDone} ]`;
}

document.addEventListener('DOMContentLoaded', () => {
    try {
        let savedZoom = localStorage.getItem('wrn_font_zoom') || "115"; 
        document.documentElement.style.fontSize = savedZoom + "%";
        const fsSelect = document.getElementById('ui-fontsize');
        if (fsSelect) fsSelect.value = savedZoom;

        const savedLang = localStorage.getItem('wrn_system_lang'); const ls = document.getElementById('ui-language');
        if (savedLang && ls) { ls.value = savedLang; }
        
        let savedTheme = localStorage.getItem('wrn_theme_style') || 'theme-dark';
        if(savedTheme === "theme-neon" || savedTheme === "theme-terminal" || savedTheme === "theme-solarpunk") savedTheme = "theme-dark";
        const ut = document.getElementById('ui-theme'); if(ut) ut.value = savedTheme;
        
        changeTheme(savedTheme); changeLanguage(); initialisiereApp(); 

        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('./sw.js').catch(err => console.log('PWA Error:', err));
        }
    } catch (e) {
        const stat = document.getElementById('status-container');
        if(stat) stat.innerText = "Kritischer Start-Fehler: " + e.message;
    }
});